/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as PanelIndexRouteImport } from './routes/_panel.index'
import { Route as PanelBrandRouteImport } from './routes/_panel.$brand'
import { Route as ApiPublicPanelRouteImport } from './routes/api/public/panel'
import { Route as PanelBrandCatRouteImport } from './routes/_panel.$brand.$cat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelBrandRoute = PanelBrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => PanelRoute,
} as any)
const ApiPublicPanelRoute = ApiPublicPanelRouteImport.update({
  id: '/api/public/panel',
  path: '/api/public/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelBrandCatRoute = PanelBrandCatRouteImport.update({
  id: '/$cat',
  path: '/$cat',
  getParentRoute: () => PanelBrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PanelIndexRoute
  '/auth': typeof AuthRoute
  '/$brand': typeof PanelBrandRouteWithChildren
  '/$brand/$cat': typeof PanelBrandCatRoute
  '/api/public/panel': typeof ApiPublicPanelRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/$brand': typeof PanelBrandRouteWithChildren
  '/': typeof PanelIndexRoute
  '/$brand/$cat': typeof PanelBrandCatRoute
  '/api/public/panel': typeof ApiPublicPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof PanelRouteWithChildren
  '/auth': typeof AuthRoute
  '/_panel/$brand': typeof PanelBrandRouteWithChildren
  '/_panel/': typeof PanelIndexRoute
  '/_panel/$brand/$cat': typeof PanelBrandCatRoute
  '/api/public/panel': typeof ApiPublicPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/$brand' | '/$brand/$cat' | '/api/public/panel'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/$brand' | '/' | '/$brand/$cat' | '/api/public/panel'
  id:
    | '__root__'
    | '/_panel'
    | '/auth'
    | '/_panel/$brand'
    | '/_panel/'
    | '/_panel/$brand/$cat'
    | '/api/public/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PanelRoute: typeof PanelRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicPanelRoute: typeof ApiPublicPanelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/$brand': {
      id: '/_panel/$brand'
      path: '/$brand'
      fullPath: '/$brand'
      preLoaderRoute: typeof PanelBrandRouteImport
      parentRoute: typeof PanelRoute
    }
    '/api/public/panel': {
      id: '/api/public/panel'
      path: '/api/public/panel'
      fullPath: '/api/public/panel'
      preLoaderRoute: typeof ApiPublicPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/$brand/$cat': {
      id: '/_panel/$brand/$cat'
      path: '/$cat'
      fullPath: '/$brand/$cat'
      preLoaderRoute: typeof PanelBrandCatRouteImport
      parentRoute: typeof PanelBrandRoute
    }
  }
}

interface PanelBrandRouteChildren {
  PanelBrandCatRoute: typeof PanelBrandCatRoute
}

const PanelBrandRouteChildren: PanelBrandRouteChildren = {
  PanelBrandCatRoute: PanelBrandCatRoute,
}

const PanelBrandRouteWithChildren = PanelBrandRoute._addFileChildren(
  PanelBrandRouteChildren,
)

interface PanelRouteChildren {
  PanelBrandRoute: typeof PanelBrandRouteWithChildren
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelBrandRoute: PanelBrandRouteWithChildren,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PanelRoute: PanelRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicPanelRoute: ApiPublicPanelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
